// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbderyhxgmaleazyambo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiZGVyeWh4Z21hbGVhenlhbWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjY3NDgsImV4cCI6MjA3MTgwMjc0OH0.my89lztu6YHke6LZMGmOKqj-Z9q4dERGrxXueBsQgZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});